#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-user-bundles
Version  : 13.0.1
Release  : 16
URL      : https://github.com/clearlinux/clr-user-bundles/archive/v13.0.1.tar.gz
Source0  : https://github.com/clearlinux/clr-user-bundles/archive/v13.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: clr-user-bundles-autostart = %{version}-%{release}
Requires: clr-user-bundles-bin = %{version}-%{release}
Requires: clr-user-bundles-license = %{version}-%{release}
Requires: clr-user-bundles-man = %{version}-%{release}
Requires: clr-user-bundles-services = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : go-github.com-BurntSushi-toml
BuildRequires : go-github.com-inconshreveable-mousetrap
BuildRequires : go-github.com-spf13-cobra
BuildRequires : go-github.com-spf13-pflag

%description
No detailed description available

%package autostart
Summary: autostart components for the clr-user-bundles package.
Group: Default

%description autostart
autostart components for the clr-user-bundles package.


%package bin
Summary: bin components for the clr-user-bundles package.
Group: Binaries
Requires: clr-user-bundles-license = %{version}-%{release}
Requires: clr-user-bundles-services = %{version}-%{release}

%description bin
bin components for the clr-user-bundles package.


%package extras
Summary: extras components for the clr-user-bundles package.
Group: Default

%description extras
extras components for the clr-user-bundles package.


%package license
Summary: license components for the clr-user-bundles package.
Group: Default

%description license
license components for the clr-user-bundles package.


%package man
Summary: man components for the clr-user-bundles package.
Group: Default

%description man
man components for the clr-user-bundles package.


%package services
Summary: services components for the clr-user-bundles package.
Group: Systemd services

%description services
services components for the clr-user-bundles package.


%prep
%setup -q -n clr-user-bundles-13.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568395751
export GCC_IGNORE_WERROR=1
export GOPROXY=file:///usr/share/goproxy
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568395751
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-user-bundles
cp COPYING %{buildroot}/usr/share/package-licenses/clr-user-bundles/COPYING
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
ln -s ../3rd-party-update.timer %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/3rd-party-update.timer
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/3rd-party-update.timer

%files bin
%defattr(-,root,root,-)
/usr/bin/3rd-party-post
/usr/bin/swupd-3rd-party

%files extras
%defattr(-,root,root,-)
/usr/bin/mixer-user-bundler
/usr/share/man/man1/mixer-user-bundler.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-user-bundles/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/3rd-party-post.1
/usr/share/man/man1/swupd-3rd-party.1

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/3rd-party-update.timer
/usr/lib/systemd/system/3rd-party-update.service
/usr/lib/systemd/system/3rd-party-update.timer
